name: 🚀 Deployment

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  type-check:
    name: ✅ Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Download deps
        run: npm ci

      - name: Check types
        run: npm run type-check

  eslint:
    name: 🧪 ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Download deps
        run: npm ci

      - name: Lint
        run: npm run lint

  prettier:
    name: 🔍 Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Download deps
        run: npm ci

      - name: Format
        run: npm run format
